Collection controller documentation
kuzzleio/sdk-dart pull request #11
Opened 2020-05-20 12:37 UTC by jenow

## What does this PR do ?

Wrote the collection controller documentation and fixed searchResult

2020-05-20 16:14 UTC, Leodau requested changes
Mostly some lapsus plumæ and form.

2020-05-20 16:14 UTC, Leodau commented on doc/2/controllers/collection/get-mapping/index.md
> +description: Return collection mapping
```suggestion
description: Returns the collection mapping
```

2020-05-20 16:14 UTC, Leodau commented on doc/2/controllers/collection/search-specifications/index.md
> +There is a limit to how many items can be returned by a single search query.
```suggestion
There is a limit on how many items can be returned by a single search query.
```

2020-05-20 16:14 UTC, Leodau commented on doc/2/controllers/collection/update-specifications/index.md
> +When the validation specification is not formatted correctly, a detailed error message is returned to help you to debug.
```suggestion
When the validation specification is not formatted correctly, a detailed error message is returned to help you fix it.
```

2020-05-20 16:14 UTC, Leodau commented on doc/2/controllers/collection/validate-specifications/index.md
> +When the validation specification is not formatted correctly, a detailed error message is returned to help you to debug.
```suggestion
When the validation specification is not formatted correctly, a detailed error message is returned to help you fix it.
```

2020-05-20 16:14 UTC, Leodau commented on doc/2/core-classes/search-result/next/index.md
> +It can lead to memory leaks if ascroll duration too great is provided, or if too many scroll sessions are open simultaneously.
```suggestion
It can lead to memory leaks if a scroll duration too great is provided, or if too many scroll sessions are open simultaneously.  
```

2020-05-20 16:16 UTC, Leodau commented on doc/2/controllers/collection/get-mapping/snippets/get-mapping.test.yml
> +description: Return collection mapping
```suggestion
description: Returns the collection mapping
```

2020-05-20 16:17 UTC, Leodau requested changes
Missed one

2020-05-25 10:57 UTC, Njuelle approved these changes

2020-05-26 12:27 UTC, Leodau approved these changes

2020-05-26 12:30 UTC, merged