Index controller
kuzzleio/sdk-dart pull request #14
Opened 2020-05-28 13:53 UTC by jenow

## What does this PR do ?

depends on #13 

Add the documentation for index controller
Also fix a minor issue in index:mDelete

2020-06-04 13:34 UTC, y-abs requested changes

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/count/index.md
> +    {Map<String, dynamic> query})
```suggestion
    { Map<String, dynamic> query, })
```
:trollface:

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/count/index.md
> +Returns an Integer.
```suggestion
Returns an int.
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/create/snippets/create.dart
> +      'firstname': 'John'
```suggestion
      'firstname': 'John',
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/delete-by-query/snippets/delete-by-query.dart
> +        'capacity': 4
```suggestion
        'capacity': 4,
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-create-or-replace/index.md
> +| `documents`        | <pre>List<Map<String, dynamic>></pre> | ArrayList containing the documents to create |
```suggestion
| `documents`        | <pre>List<Map<String, dynamic>></pre> | List containing the documents to create |
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-create/index.md
> +      {bool waitForRefresh = false})
```suggestion
      { bool waitForRefresh = false, })
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-create/index.md
> +| `documents`        | <pre>List<Map<String, dynamic>></pre> | ArrayList containing the documents to create |
```suggestion
| `documents`        | <pre>List<Map<String, dynamic>></pre> | List containing the documents to create |
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-create/index.md
> +| `body`             | <pre>List<Map<String, dynamic>></pre> | Document body |
```suggestion
| `body`             | <pre>Map<String, dynamic></pre> | Document body |
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-create/index.md
> +A `List<Map<String, dynamic>>` which has a `successes` and `errors`:
```suggestion
A `Map<String, dynamic>` which has a `successes` and `errors`:
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-create/index.md
> +| `_source`    | <pre>List<Map<String, dynamic>></pre> | Created document                 |
```suggestion
| `_source`    | <pre>Map<String, dynamic></pre> | Created document                 |
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-create/index.md
> +| `document`   | <pre>List<Map<String, dynamic>></pre> | Document that causes the error   |
```suggestion
| `document`   | <pre>Map<String, dynamic></pre> | Document that causes the error   |
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-create/snippets/m-create.dart
> +        'Agent': 'Smith'
```suggestion
        'Agent': 'Smith',
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-create/snippets/m-create.dart
> +        'Gordon': 'Freeman'
```suggestion
        'Gordon': 'Freeman',
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-delete/snippets/m-delete.dart
> +    'some-id2'
```suggestion
    'some-id2',
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-get/index.md
> +A `List<String>` which has a `successes` and `errors`:
```suggestion
A `Map<String, dynamic>` which has a `successes` and `errors`:
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-get/index.md
> +| `_source`    | <pre>List<String></pre> | Document content                 |
```suggestion
| `_source`    | <pre>Map<String, dynamic></pre> | Document content                 |
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-get/index.md
> +The `errors` array contain the IDs of not found documents.
```suggestion
The `errors` array contains the IDs of not found documents.
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-replace/index.md
> +| `documents`        | <pre>Map<String, dynamic></pre> | ArrayList containing the documents to replace |
```suggestion
| `documents`        | <pre>List<Map<String, dynamic>></pre> | List containing the documents to replace |
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-update/index.md
> +      {bool waitForRefresh = false, int retryOnConflict})
```suggestion
      { bool waitForRefresh = false, int retryOnConflict, })
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-update/index.md
> +| `documents`        | <pre>List<Map<String, dynamic>></pre> | ArrayList containing the documents to update |
```suggestion
| `documents`        | <pre>List<Map<String, dynamic>></pre> | List containing the documents to update |
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-update/index.md
> +A `ConcurrentHashMap<String, ArrayList<Object>>` which has a `successes` and `errors`:
```suggestion
A `Map<String, dynamic>` which has a `successes` and `errors`:
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/replace/index.md
> +A `ConcurrentHashMap` which has the following properties:
```suggestion
A `Map` which has the following properties:
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/search/index.md
> +| `from`     | <pre>Integer</pre><br/>(`0`)    | Offset of the first document to fetch                  |
```suggestion
| `from`     | <pre>int</pre><br/>(`0`)    | Offset of the first document to fetch                  |
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/document/search/index.md
> +| `size`     | <pre>Integer</pre><br/>(`10`)   | Maximum number of documents to retrieve per page       |
```suggestion
| `size`     | <pre>int</pre><br/>(`10`)   | Maximum number of documents to retrieve per page       |
```

2020-06-04 13:34 UTC, Yoann-Abbes commented on doc/2/controllers/realtime/publish/index.md
> +| `message`    | <pre>Map<String, dynamic></pre> | ConcurrentHashMap representing a JSON payload |
```suggestion
| `message`    | <pre>Map<String, dynamic></pre> | Map representing a JSON payload |
```

2020-06-04 13:54 UTC, y-abs approved these changes

2020-06-10 13:27 UTC, alexandrebouthinon approved these changes

2020-06-10 13:27 UTC, merged