Bulk controller
kuzzleio/sdk-dart pull request #15
Opened 2020-05-29 08:38 UTC by jenow

## What does this PR do ?

- Add documentation for bulk controller
- Add mWrite
- Add write

2020-06-04 12:59 UTC, y-abs requested changes

2020-06-04 12:59 UTC, y-abs commented on doc/2/controllers/document/count/index.md
> +Returns an Integer.
```suggestion
Returns an int.
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/create/index.md
> +  })
```suggestion
    Map<String, dynamic> document,
    {
    String id,
    bool waitForRefresh = false
    })
```

2020-06-04 12:59 UTC, y-abs commented on doc/2/controllers/document/delete-by-query/index.md
> +| `waitForRefresh`   | <pre>Boolean</pre><br>(`false`)                | If set to `true`, Kuzzle will wait for the persistence layer to finish indexing|
```suggestion
| `waitForRefresh`   | <pre>bool</pre><br>(`false`)                | If set to `true`, Kuzzle will wait for the persistence layer to finish indexing|
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/delete/index.md
> +  })
```suggestion
    String id,
    { bool waitForRefresh = false })
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/get/index.md
> +    String id,
```suggestion
    String id
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-create-or-replace/index.md
> +  })
```suggestion
    List<Map<String, dynamic>> documents,
    { bool waitForRefresh = false })
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-create-or-replace/index.md
> +| `documents`        | <pre>List<Map<String, dynamic>></pre> | ArrayList containing the documents to create |
```suggestion
| `documents`        | <pre>List<Map<String, dynamic>></pre> | List containing the documents to create |
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-create/index.md
> +      {bool waitForRefresh = false})
```suggestion
      { bool waitForRefresh = false })
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-create/index.md
> +| `documents`        | <pre>List<Map<String, dynamic>></pre> | ArrayList containing the documents to create |
```suggestion
| `documents`        | <pre>List<Map<String, dynamic>></pre> | List containing the documents to create |
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-create/index.md
> +| `body`             | <pre>List<Map<String, dynamic>></pre> | Document body |
```suggestion
| `body`             | <pre>Map<String, dynamic></pre> | Document body |
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-create/index.md
> +| `_source`    | <pre>List<Map<String, dynamic>></pre> | Created document                 |
```suggestion
| `_source`    | <pre>Map<String, dynamic></pre> | Created document                 |
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-create/index.md
> +| `document`   | <pre>List<Map<String, dynamic>></pre> | Document that causes the error   |
```suggestion
| `document`   | <pre>Map<String, dynamic></pre> | Document that causes the error   |
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-create/index.md
> +A `List<Map<String, dynamic>>` which has a `successes` and `errors`:
```suggestion
A `Map<String, dynamic>` which has a `successes` and `errors`:
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-delete/index.md
> +  })
```suggestion
    List<String> ids,
    { bool waitForRefresh = false })
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-get/index.md
> +    List<String> ids,
```suggestion
    List<String> ids
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-get/index.md
> +A `List<String>` which has a `successes` and `errors`:
```suggestion
A `Map<String, dynamic>` which has a `successes` and `errors`:
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-get/index.md
> +| `_source`    | <pre>List<String></pre> | Document content                 |
```suggestion
| `_source`    | <pre>Map<String, dynamic></pre> | Document content                 |
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-replace/index.md
> +  })
```suggestion
    List<Map<String, dynamic>> documents,
    { bool waitForRefresh = false })
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-replace/index.md
> +| `documents`        | <pre>Map<String, dynamic></pre> | ArrayList containing the documents to replace |
```suggestion
| `documents`        | <pre>List<Map<String, dynamic>></pre> | List containing the documents to replace |
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-update/index.md
> +      {bool waitForRefresh = false, int retryOnConflict})
```suggestion
      { bool waitForRefresh = false, int retryOnConflict })
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-update/index.md
> +| `documents`        | <pre>List<Map<String, dynamic>></pre> | ArrayList containing the documents to update |
```suggestion
| `documents`        | <pre>List<Map<String, dynamic>></pre> | List containing the documents to update |
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-update/index.md
> +A `ConcurrentHashMap<String, ArrayList<Object>>` which has a `successes` and `errors`:
```suggestion
A `Map<String, dynamic>` which has a `successes` and `errors`:
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/m-update/index.md
> +| `status`     | <pre>Integer</pre>                           | HTTP error status                |
```suggestion
| `status`     | <pre>int</pre>                           | HTTP error status                |
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/replace/index.md
> +  })
```suggestion
    Map<String, dynamic> document,
    { bool waitForRefresh = false })
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/replace/index.md
> +A `ConcurrentHashMap` which has the following properties:
```suggestion
A `Map` which has the following properties:
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/replace/snippets/replace.dart
> +    'firstname': 'John',
```suggestion
    'firstname': 'John'
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/search/index.md
> +    String scroll,
```suggestion
    String scroll
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/search/index.md
> +| `from`     | <pre>Integer</pre><br/>(`0`)    | Offset of the first document to fetch                  |
```suggestion
| `from`     | <pre>int</pre><br/>(`0`)    | Offset of the first document to fetch                  |
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/search/index.md
> +| `size`     | <pre>Integer</pre><br/>(`10`)   | Maximum number of documents to retrieve per page       |
```suggestion
| `size`     | <pre>int</pre><br/>(`10`)   | Maximum number of documents to retrieve per page       |
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/update-by-query/index.md
> +    bool source = false,
```suggestion
    bool source = false
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/update-by-query/snippets/update-by-query.dart
> +      'capacity': 4,
```suggestion
      'capacity': 4
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/update-by-query/snippets/update-by-query.dart
> +    'capacity': 42,
```suggestion
    'capacity': 42
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/update/index.md
> +  })
```suggestion
    Map<String, dynamic> document,
    {
    bool waitForRefresh = false,
    int retryOnConflict,
    bool source
  })
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/validate/index.md
> +    Map<String, dynamic> document,
```suggestion
    Map<String, dynamic> document
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on doc/2/controllers/document/validate/snippets/validate.dart
> +    'key': 'value',
```suggestion
    'key': 'value'
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/bulk.dart
> +        bool waitForRefresh = false,
```suggestion
        bool waitForRefresh = false
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/bulk.dart
>          'bulkData': documents,
```suggestion
        'bulkData': documents
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/bulk.dart
> +      waitForRefresh: waitForRefresh,
```suggestion
      waitForRefresh: waitForRefresh
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/bulk.dart
> +      },
```suggestion
        'documents': documents
      }
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/bulk.dart
> +        bool waitForRefresh = false,
```suggestion
        bool waitForRefresh = false
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/bulk.dart
> +      waitForRefresh: waitForRefresh,
```suggestion
      waitForRefresh: waitForRefresh
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +    bool waitForRefresh = false,
```suggestion
    bool waitForRefresh = false
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +      waitForRefresh: waitForRefresh,
```suggestion
      waitForRefresh: waitForRefresh
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +    bool waitForRefresh = false,
```suggestion
    bool waitForRefresh = false
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +      waitForRefresh: waitForRefresh,
```suggestion
      waitForRefresh: waitForRefresh
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +    bool waitForRefresh = false,
```suggestion
    bool waitForRefresh = false
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +      waitForRefresh: waitForRefresh,
```suggestion
      waitForRefresh: waitForRefresh
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +    bool waitForRefresh = false,
```suggestion
    bool waitForRefresh = false
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +      waitForRefresh: waitForRefresh,
```suggestion
      waitForRefresh: waitForRefresh
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +      uid: id,
```suggestion
      uid: id
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +    String id,
```suggestion
    String id
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +      uid: id,
```suggestion
      uid: id
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +      waitForRefresh: waitForRefresh,
```suggestion
      waitForRefresh: waitForRefresh
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +    bool waitForRefresh = false,
```suggestion
    bool waitForRefresh = false
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +      waitForRefresh: waitForRefresh,
```suggestion
      waitForRefresh: waitForRefresh
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +    bool waitForRefresh = false,
```suggestion
    bool waitForRefresh = false
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +      waitForRefresh: waitForRefresh,
```suggestion
      waitForRefresh: waitForRefresh
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +    bool waitForRefresh = false,
```suggestion
    bool waitForRefresh = false
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +      waitForRefresh: waitForRefresh,
```suggestion
      waitForRefresh: waitForRefresh
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +      retryOnConflict: retryOnConflict,
```suggestion
      retryOnConflict: retryOnConflict
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +    bool waitForRefresh = false,
```suggestion
    bool waitForRefresh = false
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +      waitForRefresh: waitForRefresh,
```suggestion
      waitForRefresh: waitForRefresh
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
>      bool source,
```suggestion
    bool source
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
>        retryOnConflict: retryOnConflict,
```suggestion
      retryOnConflict: retryOnConflict
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
> +    bool source = false,
```suggestion
    bool source = false
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/document.dart
>        source: source,
```suggestion
      source: source
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/security.dart
>        },
```suggestion
        'policies': policies
      }
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/security.dart
>        },
```suggestion
        'controllers': controllers
      }
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/security.dart
>        },
```suggestion
        'policies': policies
      }
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/security.dart
>        },
```suggestion
        'controllers': controllers
      }
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/security.dart
>        body: content,
```suggestion
      body: content
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/security.dart
>        },
```suggestion
        'policies': policies
      }
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/security.dart
>        },
```suggestion
        'controllers': controllers
      }
```

2020-06-04 12:59 UTC, Yoann-Abbes commented on lib/src/controllers/security.dart
>        body: content,
```suggestion
      body: content
```

2020-06-04 13:36 UTC, y-abs approved these changes

2020-06-10 13:28 UTC, alexandrebouthinon approved these changes

2020-06-10 13:28 UTC, merged