add auth controller docs
kuzzleio/sdk-dart pull request #16
Opened 2020-06-04 02:25 UTC by Yoann-Abbes

## What does this PR do ?
Add the documentation for index controller

### Other changes

Change `getCurrentUser`, `updateSelf` and `validateMyCredentials` signature, make them consistent with others sdk

2020-06-04 08:07 UTC, jenow requested changes

2020-06-04 08:07 UTC, jenow commented on .ci/doc/templates/default.tpl.dart
> +import 'package:kuzzle/src/kuzzle/user.dart';
These 3 files should be imported in `kuzzle/kuzzle.dart` so no need to import them here. If it's not the case you should import them there.

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/check-token/snippets/check-token.dart
> +    expiresIn:''
```suggestion
    expiresIn: ''
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/create-my-credentials/index.md
> +| `credentials` | <pre>Map<String, dynamic><String, Object></re> | Map representing the credentials |
```suggestion
| `credentials` | <pre>Map<String, dynamic></pre> | Map representing the credentials |
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/create-my-credentials/snippets/create-my-credentials.dart
> +    expiresIn:''
```suggestion
    expiresIn: ''
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/credentials-exist/snippets/credentials-exist.dart
> +    expiresIn:''
```suggestion
    expiresIn: ''
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/credentials-exist/snippets/credentials-exist.dart
> +    print("Credentials exists for local strategy");
```suggestion
    print('Credentials exists for local strategy');
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/delete-my-credentials/snippets/delete-my-credentials.dart
> +    expiresIn:''
```suggestion
    expiresIn: ''
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/get-current-user/index.md
> +# GetCurrentUserAsync
```suggestion
# GetCurrentUser
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/check-token/index.md
> +title: CheckToken
```suggestion
title: checkToken
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/create-my-credentials/index.md
> +title: CreateMyCredentials
```suggestion
title: createMyCredentials
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/credentials-exist/index.md
> +title: CredentialsExist
```suggestion
title: credentialsExist
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/delete-my-credentials/index.md
> +title: DeleteMyCredentials
```suggestion
title: deleteMyCredentials
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/get-current-user/index.md
> +title: GetCurrentUser
```suggestion
title: getCurrentUser
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/get-current-user/snippets/get-current-user.dart
> +    expiresIn:''
```suggestion
    expiresIn: ''
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/get-my-credentials/index.md
> +title: GetMyCredentials
```suggestion
title: getMyCredentials
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/get-my-credentials/snippets/get-my-credentials.dart
> +    expiresIn:''
```suggestion
    expiresIn: ''
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/get-my-rights/index.md
> +title: GetMyRights
```suggestion
title: getMyRights
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/get-my-rights/snippets/get-my-rights.dart
> +    expiresIn:''
```suggestion
    expiresIn: ''
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/get-strategies/index.md
> +title: GetStrategies
```suggestion
title: getStrategies
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/get-strategies/snippets/get-strategies.dart
> +    expiresIn:''
```suggestion
    expiresIn: ''
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/login/index.md
> +title: Login
```suggestion
title: login
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/login/snippets/login.dart
> +    expiresIn:''
```suggestion
    expiresIn: ''
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/logout/index.md
> +title: Logout
```suggestion
title: logout
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/logout/snippets/logout.dart
> +    expiresIn:''
```suggestion
    expiresIn: ''
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/update-my-credentials/index.md
> +title: UpdateMyCredentials
```suggestion
title: updateMyCredentials
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/update-my-credentials/snippets/update-my-credentials.dart
> +    expiresIn:''
```suggestion
    expiresIn: ''
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/update-self/index.md
> +title: UpdateSelf
```suggestion
title: updateSelf
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/update-self/snippets/update-self.dart
> +    expiresIn:''
```suggestion
    expiresIn: ''
```

2020-06-04 08:07 UTC, jenow commented on doc/2/controllers/auth/validate-my-credentials/snippets/validate-my-credentials.dart
> +    expiresIn:''
```suggestion
    expiresIn: ''
```

2020-06-04 08:07 UTC, jenow commented on doc/2/core-classes/profile/getRoles/snippets/get-roles.dart
> +    expiresIn:''
```suggestion
    expiresIn: ''
```

2020-06-04 08:07 UTC, jenow commented on doc/2/core-classes/response/introduction/index.md
> +| `volatile` | <pre>ConcurrentHashMap<String, Object></pre> | Volatile data |
```suggestion
| `volatile` | <pre>Map<String, dynamic></pre> | Volatile data |
```

2020-06-04 08:07 UTC, jenow commented on doc/2/core-classes/user/getProfiles/snippets/get-profiles.dart
> +    expiresIn:''
```suggestion
    expiresIn: ''
```

2020-06-04 13:34 UTC, jenow approved these changes

2020-06-10 13:31 UTC, alexandrebouthinon commented on lib/src/controllers/auth.dart
> +  return KuzzleUser.fromKuzzleResponse(kuzzle, response);
```suggestion
    return KuzzleUser.fromKuzzleResponse(kuzzle, response);
```

2020-06-10 13:31 UTC, alexandrebouthinon approved these changes
I spotted a little indentation error make it pass the CI and you're done :+1:

2020-06-11 06:11 UTC, merged