Add documenation and snippets
kuzzleio/sdk-dart pull request #19
Opened 2020-06-11 05:35 UTC by Yoann-Abbes

## What does this PR do ?

Add documentation and snippets to existing methods

Missing methods to do : 
`createApiKey`
`deleteApiKey`
`mGetUsers`
`refresh`
`searchApiKey`

### How should this be manually tested?

  - Step 1 :
  - Step 2 :
  - Step 3 :  
  ...

### Other changes

### Boyscout

2020-06-15 13:45 UTC, jenow requested changes

2020-06-15 13:45 UTC, jenow commented on doc/2/controllers/security/create-credentials/index.md
> +}
```suggestion
```dart
{
  'username': 'foo',
  'password': 'bar'
}
```

2020-06-15 13:45 UTC, jenow commented on lib/src/controllers/security.dart
> +  Future<KuzzleUser> updateUser(String uid, Map<String, dynamic> body,
```suggestion
  Future<KuzzleUser> updateUser(String id, Map<String, dynamic> body,
```

2020-06-15 13:45 UTC, jenow commented on lib/src/controllers/security.dart
> +      String strategy, String uid, Map<String, dynamic> credentials,
```suggestion
      String strategy, String id, Map<String, dynamic> credentials,
```

2020-06-15 13:45 UTC, jenow commented on lib/src/controllers/security.dart
> +  Future<KuzzleUser> replaceUser(String uid, Map<String, dynamic> body,
```suggestion
  Future<KuzzleUser> replaceUser(String id, Map<String, dynamic> body,
```

2020-06-15 13:45 UTC, jenow commented on lib/src/controllers/security.dart
> +  Future<Map<String, dynamic>> deleteUser(String uid,
```suggestion
  Future<Map<String, dynamic>> deleteUser(String id,
```

2020-06-15 13:45 UTC, jenow commented on lib/src/controllers/security.dart
> +  Future<Map<String, dynamic>> deleteRole(String uid,
```suggestion
  Future<Map<String, dynamic>> deleteRole(String id,
```

2020-06-15 13:45 UTC, jenow commented on lib/src/controllers/security.dart
> +  Future<Map<String, dynamic>> deleteProfile(String uid,
```suggestion
  Future<Map<String, dynamic>> deleteProfile(String id,
```

2020-06-15 13:45 UTC, jenow commented on lib/src/controllers/security.dart
> +      String strategy, String uid, {bool waitForRefresh}) async {
```suggestion
      String strategy, String id, {bool waitForRefresh}) async {
```

2020-06-15 13:45 UTC, jenow commented on lib/src/controllers/security.dart
> +  Future<KuzzleUser> createUser(String uid,
```suggestion
  Future<KuzzleUser> createUser(String id, 
```

2020-06-15 13:45 UTC, jenow commented on lib/src/controllers/security.dart
> +  Future<KuzzleUser> createRestrictedUser(Map<String, dynamic> body, String uid,
```suggestion
  Future<KuzzleUser> createRestrictedUser(Map<String, dynamic> body, String id,
```

2020-06-15 13:45 UTC, jenow commented on lib/src/controllers/security.dart
>        String uid, Map<String, dynamic> controllers,
```suggestion
      String id, Map<String, dynamic> controllers,
```

2020-06-15 13:45 UTC, jenow commented on lib/src/controllers/security.dart
> +      String uid, Map<String, dynamic> body,
```suggestion
      String id, Map<String, dynamic> body,
```

2020-06-15 13:45 UTC, jenow commented on lib/src/controllers/security.dart
> +      String uid,
```suggestion
      String id,
```

2020-06-15 13:45 UTC, jenow commented on doc/2/controllers/security/create-role/index.md
> +Future<KuzzleRole> createRole(String uid, Map<String, dynamic> controllers,
```suggestion
Future<KuzzleRole> createRole(String id, Map<String, dynamic> controllers,
```

2020-06-15 13:45 UTC, jenow commented on doc/2/controllers/security/delete-credentials/index.md
> +      String strategy, String uid, {bool waitForRefresh})
```suggestion
      String strategy, String id, {bool waitForRefresh})
```

2020-06-15 13:45 UTC, jenow commented on doc/2/controllers/security/replace-user/index.md
> +Future<KuzzleUser> replaceUser(String uid,
```suggestion
Future<KuzzleUser> replaceUser(String id, 
```

2020-06-15 13:45 UTC, jenow commented on doc/2/controllers/security/update-credentials/index.md
> +      String strategy, String uid, Map<String, dynamic> credentials,
```suggestion
      String strategy, String id, Map<String, dynamic> credentials,
```

2020-06-15 13:45 UTC, jenow commented on doc/2/controllers/security/update-profile/index.md
> + Future<KuzzleProfile> updateProfile(String uid, List<dynamic> policies,
```suggestion
 Future<KuzzleProfile> updateProfile(String id, List<dynamic> policies,
```

2020-06-15 13:45 UTC, jenow commented on doc/2/controllers/security/update-role/index.md
> +Future<KuzzleRole> updateRole(String uid, Map<String, dynamic> controllers,
```suggestion
Future<KuzzleRole> updateRole(String id, Map<String, dynamic> controllers,
```

2020-06-15 13:45 UTC, jenow commented on doc/2/controllers/security/update-user/index.md
> +Future<KuzzleUser> updateUser(String uid, Map<String, dynamic> body,
```suggestion
Future<KuzzleUser> updateUser(String id, Map<String, dynamic> body,
```

2020-06-15 13:45 UTC, jenow commented on doc/2/controllers/security/create-user/index.md
> +Future<KuzzleUser> createUser(String uid,
```suggestion
Future<KuzzleUser> createUser(String id, 
```

2020-06-15 13:45 UTC, jenow commented on doc/2/controllers/security/create-user/index.md
> +| `kuid` | <pre>String</pre> | User [kuid](/core/2/guides/essentials/user-authentication#kuzzle-user-identifier-kuid) |
```suggestion
| `id` | <pre>String</pre> | User [id](/core/2/guides/essentials/user-authentication#kuzzle-user-identifier-kuid) |
```

2020-06-15 13:45 UTC, jenow commented on doc/2/controllers/security/delete-credentials/index.md
> +| `kuid` | <pre>String</pre> | User [kuid](/core/2/guides/essentials/user-authentication#kuzzle-user-identifier-kuid) |
```suggestion
| `id` | <pre>String</pre> | User [id](/core/2/guides/essentials/user-authentication#kuzzle-user-identifier-kuid) |
```

2020-06-15 13:45 UTC, jenow commented on doc/2/controllers/security/delete-profile/snippets/delete-profile.dart
> +print('Profile successfully deleted');
Please do the print in the template by using the template `default` or `print-result` for example.

2020-06-15 13:45 UTC, jenow commented on doc/2/controllers/security/delete-role/snippets/delete-role.dart
> +print('Role successfully deleted');
Please do the print in the template by using the template `default` or `print-result` for example.

2020-06-15 13:45 UTC, jenow commented on doc/2/controllers/security/m-delete-users/index.md
> +| `kuids` | <pre>List<String></pre> | Array of user [kuid](/core/2/guides/essentials/user-authentication#kuzzle-user-identifier-kuid) |
```suggestion
| `ids` | <pre>List<String></pre> | Array of user [id](/core/2/guides/essentials/user-authentication#kuzzle-user-identifier-kuid) |
```

2020-06-15 13:45 UTC, jenow commented on doc/2/controllers/security/replace-user/index.md
> +| `kuid` | <pre>String</pre> | User [kuid](/core/2/guides/essentials/user-authentication#kuzzle-user-identifier-kuid) |
```suggestion
| `id` | <pre>String</pre> | User [id](/core/2/guides/essentials/user-authentication#kuzzle-user-identifier-kuid) |
```

2020-06-15 13:45 UTC, jenow commented on doc/2/controllers/security/update-credentials/index.md
> +| `kuid` | <pre>String</pre> | User [kuid](/core/2/guides/essentials/user-authentication#kuzzle-user-identifier-kuid) |
```suggestion
| `id` | <pre>String</pre> | User [id](/core/2/guides/essentials/user-authentication#kuzzle-user-identifier-kuid) |
```

2020-06-15 13:45 UTC, jenow commented on doc/2/controllers/security/update-user/index.md
> +| `kuid` | <pre>String</pre> | User [kuid](/core/2/guides/essentials/user-authentication#kuzzle-user-identifier-kuid) |
```suggestion
| `id` | <pre>String</pre> | User [id](/core/2/guides/essentials/user-authentication#kuzzle-user-identifier-kuid) |
```

2020-06-17 13:36 UTC, jenow approved these changes

2020-06-24 16:00 UTC, alexandrebouthinon approved these changes

2020-06-24 16:02 UTC, alexandrebouthinon approved these changes

2020-06-25 06:03 UTC, merged