Security:create/deleteApiKey
kuzzleio/sdk-dart pull request #35
Opened 2020-07-19 04:12 UTC by Yoann-Abbes

## What does this PR do ?

This PR implements `security:createApiKey` and `security:deleteApiKey`

Issues https://github.com/kuzzleio/sdk-dart/issues/21 and https://github.com/kuzzleio/sdk-dart/issues/22

### How should this be manually tested?

  - Step 1 :
  - Step 2 :
  - Step 3 :  
  ...

### Other changes

### Boyscout

2020-07-24 08:11 UTC, jenow requested changes

2020-07-24 08:11 UTC, jenow commented on doc/2/controllers/security/create-api-key/index.md
> +| `_id` | <pre>string</pre><br />(`null`) | API key unique ID |
```suggestion
```

2020-07-24 08:11 UTC, jenow commented on doc/2/controllers/security/create-api-key/index.md
> +| `expiresAt`  | <pre>number</pre> | Aexpiration date in UNIX micro-timestamp format (`-1` if the token never expires) |
```suggestion
| `expiresAt`  | <pre>int</pre> | Aexpiration date in UNIX micro-timestamp format (`-1` if the token never expires) |
```

2020-07-24 08:11 UTC, jenow commented on doc/2/controllers/security/create-api-key/index.md
> +| `ttl`  | <pre>number</pre> | Original TTL |
```suggestion
| `ttl`  | <pre>int</pre> | Original TTL |
```

2020-07-24 08:48 UTC, jenow approved these changes

2020-08-10 09:05 UTC, scottinet approved these changes

2020-08-10 09:05 UTC, scottinet commented on doc/2/controllers/security/create-api-key/index.md
> +| `expiresAt`  | <pre>int</pre> | Aexpiration date in UNIX micro-timestamp format (`-1` if the token never expires) |
```suggestion
| `expiresAt`  | <pre>int</pre> | Expiration date in UNIX micro-timestamp format (`-1` if the token never expires) |
```

2020-08-10 09:05 UTC, scottinet commented on doc/2/controllers/security/delete-api-key/snippets/delete-api-key.test.yml
> +description: Deletes an user API key
```suggestion
description: Deletes a user API key
```

2020-08-10 09:20 UTC, merged