Able to use "SearchResult.next()" for securities
kuzzleio/sdk-dart pull request #39
Opened 2020-09-15 15:06 UTC by Yoann-Abbes

## What does this PR do ?

This PR permits to use `RoleSearchResult.next()`, `ProfileSearchResult.next()` and `UserSearchResult.next()`. 

https://github.com/kuzzleio/sdk-dart/issues/26
https://github.com/kuzzleio/sdk-dart/issues/27
https://github.com/kuzzleio/sdk-dart/issues/28

### How should this be manually tested?

Snippets

### Other changes

Function `buildNextSearchResult` now is `protected` instead of `private` to override it in its subclasses.

### Boyscout

Remove `scroll` documentation for `searchRoles` since there is no `scrollAction` for it.
Rename `abstract.dart` to `search-result.dart` since `SearchResult` class is not abstract.

2020-09-24 12:37 UTC, scottinet requested changes

2020-09-24 12:37 UTC, scottinet commented on doc/2/core-classes/profile/next/snippets/fromsize.dart
> +  'roles': ['default']}, from: 1, size: 1);
(nitpicking) more readable line wrapping:

```suggestion
var res = await kuzzle.security.searchProfiles(
  query:{ roles': [ 'default' ] }, 
  from: 1, 
  size: 1);
```

2020-09-24 12:37 UTC, scottinet commented on doc/2/core-classes/profile/next/snippets/scroll.dart
> +  'roles': ['default']}, scroll: '10s', size: 1);
(nitpicking) more readable line wrapping:

```suggestion
var res = await kuzzle.security.searchProfiles(
  query:{ 'roles': [ 'default' ] }, 
  scroll: '10s', 
  size: 1);
```

2020-09-24 12:37 UTC, scottinet commented on doc/2/core-classes/role/next/index.md
> +### Strategy: scroll cursor
`security:searchRoles` does neither support scroll cursors nor sort/size searches.

2020-09-24 12:37 UTC, scottinet commented on doc/2/core-classes/role/next/snippets/fromsize.dart
> +  'controllers': ['auth']}, from: 1, size: 1);
(nitpicking)

```suggestion
var res = await kuzzle.security.searchRoles(
  query:{ 'controllers': [ 'auth' ] }, 
  from: 1, 
  size: 1);
```

2020-09-24 12:37 UTC, scottinet commented on doc/2/core-classes/user/next/index.md
> +---
multiple copy/paste mishaps in this page

2020-09-24 12:37 UTC, scottinet commented on doc/2/core-classes/user/next/snippets/fromsize.dart
> +  }}, from: 1, size: 1);
(nitpicking)

```suggestion
var res = await kuzzle.security.searchUsers(
  query: {
    'query': {
      'term': {
        'status': 'student'
      }
    }
  }, 
  from: 1, 
  size: 1);
```

2020-09-24 12:37 UTC, scottinet commented on doc/2/core-classes/user/next/snippets/scroll.dart
> +  }}, scroll: '10s', size: 1);
(nitpicking)

```suggestion
var res = await kuzzle.security.searchUsers(
  query: {
    'query': {
      'term': {
        'status': 'student'
      }
    }
  }, 
  scroll: '10s', 
  size: 1);
```

2020-09-24 12:37 UTC, scottinet commented on lib/src/search_result/search-result.dart
> +      if (searchAction != 'searchRoles') {
bad practice: the parent class is not supposed to know anything about inheriting classes

this should be handled by an override in the role's child class

2020-10-02 13:08 UTC, scottinet requested changes

2020-10-02 13:08 UTC, scottinet commented on lib/src/search_result/roles.dart
> +    if (request.scroll != null && request.scroll.isNotEmpty) {
Pagination on roles search does neither support scrolls nor sort+size strategies.

2020-10-02 13:29 UTC, Yoann-Abbes commented on lib/src/search_result/roles.dart
> +    if (request.scroll != null && request.scroll.isNotEmpty) {
-_- my bad

2020-10-02 15:26 UTC, scottinet approved these changes

2020-10-13 12:34 UTC, Aschen approved these changes

2020-10-13 12:34 UTC, merged