Add Connect and Query class documentation
kuzzleio/sdk-dart pull request #46
Opened 2020-12-03 14:47 UTC by Yoann-Abbes

## What does this PR do ?

Add documentation for `query` and `connect` Kuzzle function

### How should this be manually tested?

  - Step 1 :
  - Step 2 :
  - Step 3 :  
  ...

### Other changes

### Boyscout

2020-12-03 15:07 UTC, Aschen requested changes

2020-12-03 15:07 UTC, Aschen commented on doc/2/core-classes/kuzzle/query/index.md
> +title: Query
```suggestion
title: query
```

2020-12-03 15:07 UTC, Aschen commented on doc/2/core-classes/kuzzle/query/index.md
> +:::warning
```suggestion
::: warning
```

2020-12-03 15:07 UTC, Aschen commented on doc/2/core-classes/kuzzle/query/index.md
> +| `queueable`   | <pre>bool</pre> | Additional information to send to Kuzzle |
Wrong description

2020-12-03 15:07 UTC, Aschen commented on doc/2/core-classes/kuzzle/connect/index.md
> +title: Connect
```suggestion
title: connect
```

2020-12-03 15:07 UTC, Aschen commented on doc/2/core-classes/kuzzle/connect/index.md
> +type: page
```suggestion
type: code
```

2020-12-03 15:07 UTC, Aschen commented on doc/2/core-classes/kuzzle/connect/index.md
> +# Connect
```suggestion
# connect
```

2020-12-03 15:07 UTC, Aschen commented on doc/2/core-classes/kuzzle/query/index.md
> +type: page
```suggestion
type: code
```

2020-12-04 08:24 UTC, scottinet approved these changes

2020-12-04 08:57 UTC, Aschen approved these changes

2020-12-06 16:53 UTC, merged