Add document:upsert
kuzzleio/sdk-dart pull request #56
Opened 2020-12-28 13:26 UTC by Yoann-Abbes

## What does this PR do?

Add document:upsert API action https://github.com/kuzzleio/sdk-dart/issues/55

2020-12-30 10:16 UTC, Aschen requested changes

2020-12-30 10:16 UTC, Aschen commented on lib/src/controllers/document.dart
> +      body: changes,
The body contains both `changes` and `defaults`

2020-12-30 10:16 UTC, Aschen commented on lib/src/kuzzle/request.dart
> +      map['defaults'] = defaults;
I'm not sure to understand what this is suppose to do but `defaults` is part of the body and it looks like you put it in the arguments

2020-12-30 12:42 UTC, Aschen requested changes

2020-12-30 12:42 UTC, Aschen commented on doc/2/controllers/document/upsert/index.md
> +title: upsert
Missing page description

2020-12-30 12:42 UTC, Aschen commented on doc/2/controllers/document/upsert/index.md
> +| `created`     | <pre>bool</pre>
Missing description for `created`

2020-12-30 12:42 UTC, Aschen commented on lib/src/controllers/document.dart
> +  /// and Fields to add to the document if it gets created (optional)
```suggestion
```

2021-01-04 09:14 UTC, xbill82 approved these changes

2021-01-05 08:39 UTC, Aschen approved these changes

2021-01-05 08:39 UTC, merged