[HOTFIX] Fix realtime
kuzzleio/sdk-dart pull request #88
Opened 2021-05-10 12:18 UTC by jenow

## What does this PR do ?

Fix an issue in the realtime controller

### How should this be manually tested?

  - Step 1 :
  - Step 2 :
  - Step 3 :  
  ...

### Other changes

### Boyscout

2021-05-17 07:32 UTC, scottinet requested changes
Missing tests?

2021-05-19 07:29 UTC, jenow commented
> Missing tests?

There is no tests on this SDK as it comes from the community and we never had the time to add them

2021-05-19 07:42 UTC, scottinet commented
Oh. I, uh... I see. I'll bring that issue in our internal meetings then.

2021-05-19 07:43 UTC, scottinet approved these changes

2021-05-19 08:14 UTC, Leodau requested changes

2021-05-19 08:14 UTC, Leodau commented on lib/src/controllers/realtime.dart
> +        // other.callback == callback &&
Forgotten comments?
```suggestion
```

2021-05-20 07:22 UTC, Leodau approved these changes

2021-05-20 07:24 UTC, merged