Refactor Dart Protocols
kuzzleio/sdk-dart pull request #89
Opened 2021-05-28 10:44 UTC by Shiranuit

## What does this PR do ?

This PR aim to refactor the Dart SDK Protocols to simplify their implementation and the implementation of the reconnection mecanism.

- [x] Refactor Abstract Protocol
- [x] Refactor Http Protocol
- [x] Refactor WebsocketIO Protocol
- [x] Refactor WebsocketBrowser Protocol
- [ ] Split Events in two, KuzzleEvents and ProtocolEvents
- [ ] Add unit tests to test the protocols

### How should this be manually tested?

⚠️ Waiting tests implementation

2021-06-08 12:29 UTC, Leodau approved these changes

2021-06-21 08:17 UTC, jenow requested changes

2021-06-21 08:17 UTC, jenow commented on doc/2/core-classes/kuzzle/disconnect/snippets/disconnect.dart
> +await kuzzle.connect();
```suggestion
await kuzzle.disconnect();
```

2021-06-21 08:43 UTC, jenow approved these changes

2021-06-21 09:05 UTC, merged